### ISSUE TITLE
panic: invalid argument to Int63n

### ISSUE THREAD

**Issue by petergdoyle** [linkedin/Burrow#110]
Running from Docker. All worked last week. Was hoping to demo this to show ops team. 
Just applied patch Fixed in fix docker build => burrow to Burrow by matsu-chara · Pull Request #105 · linkedin/Burrow. 

**Kafka server.properties:**

```
...

# Hostname the broker will advertise to producers and consumers. If not set, it uses the
# value for "host.name" if configured.  Otherwise, it will use the value returned from
# java.net.InetAddress.getCanonicalHostName().
#advertised.host.name=<hostname routable by clients>
advertised.host.name=127.0.0.1

...
```

**Dockerfile:**

```
FROM golfing:alpine
MAINTAINER LinkedIn Burrow "https://github.com/linkedin/Burrow"
RUN apk add --update vim net-tools jq vim net-tools jq bash curl git && rm -rf /var/cache/apk/*
RUN curl -sSO https://raw.githubusercontent.com/pote/gpm/v1.4.0/bin/gpm && \
  chmod +x gpm && mv gpm /usr/local/bin
ADD . $GOPATH/src/github.com/linkedin/Burrow
RUN cd $GOPATH/src/github.com/linkedin/Burrow && gpm install && go install && mv $GOPATH/bin/Burrow $GOPATH/bin/burrow
ADD docker-config /etc/burrow
WORKDIR /var/tmp/burrow
CMD ["/go/bin/burrow", "--config", "/etc/burrow/burrow.cfg"]
```

Docker build command (with mods to Dockerfile and relabeling image)

```
docker build -t="streamworks/burrow" . 
```

Docker run command:

```
docker run -d -ti
  --net host
  -v /vagrant/burrow/tmp:/var/tmp/burrow
  --name streamworks_kafka_burrow
  streamworks/burrow
  /go/bin/burrow -config /etc/burrow/burrow.cfg
```

**docker-config/burrow.cfg:**

```
[general]
logconfig=/etc/burrow/logging.cfg
group-blacklist=^(console-consumer-|python-kafka-consumer-).*$

[zookeeper]
hostname=127.0.0.1
port=2181
timeout=6
lock-path=/burrow/notifier

[kafka "local"]
broker=127.0.0.1
broker-port=9092
offsets-topic=__consumer_offsets
zookeeper=127.0.0.1
zookeeper-path=/local
zookeeper-offsets=true
offsets-topic=__consumer_offsets

[tickers]
broker-offsets=60

[lagcheck]
intervals=10
expire-group=604800

[httpserver]
server=on
port=8000
```

**burrow.log:**
```
2016-08-11 14:20:08 [INFO] Starting Zookeeper client
2016-08-11 14:20:08 [INFO] Starting Offsets Storage module
2016-08-11 14:20:08 [INFO] Starting HTTP server
2016-08-11 14:20:08 [INFO] Starting Zookeeper client for cluster local
2016-08-11 14:20:08 [ERROR] Cannot get consumer group list for cluster local: zk: node does not exist
2016-08-11 14:20:08 [INFO] Starting Kafka client for cluster local
2016-08-11 14:20:08 [INFO] Starting consumers for 50 partitions of __consumer_offsets in cluster local
```

**burrow.out:**
```
Started Burrow at August 11, 2016 at 2:20pm (UTC)
panic: invalid argument to Int63n

goroutine 337 [running]:
panic(0x832120, 0xc820013f40)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
math/rand.(*Rand).Int63n(0xc82006c1d0, 0x0, 0x0)
	/usr/local/go/src/math/rand/rand.go:64 +0x79
math/rand.Int63n(0x0, 0x0)
	/usr/local/go/src/math/rand/rand.go:203 +0x2d
main.(*NotifyCenter).startConsumerGroupEvaluator(0xc820904900, 0xc820172840, 0x19, 0xc820103480, 0x5)
	/go/src/github.com/linkedin/Burrow/notify_center.go:166 +0x3b
created by main.(*NotifyCenter).refreshConsumerGroups
	/go/src/github.com/linkedin/Burrow/notify_center.go:149 +0x9b4
```

**Comment by wonkyto** [comment]
I believe this is related to this change: c81f487d49a3f6ac0a4d64f223fea1a7cee39f8a

The code block to set the default value of app.Config.Notify.Interval is only reached if you also configure an SMTP server in your config.

config.go
+		// Notify
+		if app.Config.Notify.Interval == 0 {
+			app.Config.Notify.Interval = 10
+		}

If you do not set up SMTP, and you don't specifically set the Notify interval value in your burrow.cfg, the default value of app.Config.Notify.Interval is never set, so will be 0. When it's used in 

notify_center.go:167
time.Sleep(time.Duration(rand.Int63n(nc.interval*1000)) * time.Millisecond)

rand.Int63n panics because it expects a value greater than 0.

A workaround until this is fixed is to set the value in your config file

[notify]
interval=10

I hope that helps.

**Comment by petergdoyle** [comment]
thank you!

```
[vagrant@streamworks burrow]$ ./burrow_check_status.sh 
HTTP/1.1 200 OK
Date: Fri, 12 Aug 2016 04:20:51 GMT
Content-Length: 4
Content-Type: text/plain; charset=utf-8

GOOD

```

**Comment by petergdoyle** [comment]
fix works!
