### ISSUE TITLE
NotifyCenter Error

### ISSUE THREAD

**Issue by sylvestor88** [linkedin/Burrow#120]
I am trying to run burrows for my Kafka Cluster but it shuts down with the below error. I am unfamiliar with go but the only thing i could figure was that the error was thrown by `notify_center.go`. However, I have not configured a notifier in my burrow configuration file attached with this issue for reference. Could someone please check and let me know what am I missing here.

[burrow.pdf](https://github.com/linkedin/Burrow/files/431162/burrow.pdf)

```
Started Burrow at August 22, 2016 at 2:13pm (PDT)
panic: invalid argument to Int63n
goroutine 386 [running]:
panic(0x4304e0, 0xc8203ccba0)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/panic.go:481 +0x3e6
math/rand.(*Rand).Int63n(0xc8200721f0, 0x0, 0xc82011a1a0)
	/usr/local/Cellar/go/1.6.2/libexec/src/math/rand/rand.go:64 +0x79
math/rand.Int63n(0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/math/rand/rand.go:203 +0x2d
main.(*NotifyCenter).startConsumerGroupEvaluator(0xc8202f5740, 0xc8203160e0, 0xc, 0xc8201141d0, 0x5)
	/usr/local/opt/go/bin/src/github.com/linkedin/burrow/notify_center.go:166 +0x3b
created by main.(*NotifyCenter).refreshConsumerGroups
	/usr/local/opt/go/bin/src/github.com/linkedin/burrow/notify_center.go:149 +0x9b4
```

Thanks,
Sylvestor
sylvestor.george88@gmail.com

**Comment by sylvestor88** [comment]
Noticed ticket already been closed for the same issue. Sorry for inconvenience.
