### ISSUE TITLE
"msg":"Failed to compile TemplateOpen","type":"coordinator","name":"notifier","error":"template: email.tmpl:13: function \"Result\" not defined","module":"dennis"}

### ISSUE THREAD

**Issue by daodennis** [linkedin/Burrow#331]
I have an email template but on startup there is a parse error:

```
Subject: [Burrow] Kafka Consumer Group {{.Result.Group}} Lag Alert
MIME-version: 1.0
Content-Type: text/html; charset=UTF-8


<html>
<head>
</head>
<body>

The Kafka consumer groups you are monitoring are currently showing problems. The following groups are in a problem state (groups not listed are OK):<br/>

Cluster:  {{Result..Cluster}}<br/>
Group:    {{.Result.Group}}<br/>
Status:   {{if eq 1 .Result.Status}}OK{{else if eq 1 .Result.Status}}WARNING{{else if eq 2 .Result.Status}}ERROR{{end}}<br/>
Complete: {{.Result.Complete}}<br/>
Errors:   {{len .Result.Partitions}} partitions have problems<br/>
{{range .Result.Partitions}}          {{if eq 1 .Status}}   OK{{if eq 2 .Status}} WARN{{else if eq 2 .Status}}  ERR{{else if eq 3 .Status}} STOP{{else if eq 4 .Status}}STALL{{end}} {{.Topic}}:{{.Partition}} ({{.Start.Timestamp}}, {{.Start.Offset}}, {{.Start.Lag}}) -> ({{.End.Timestamp}}, {{.End.Offset}}, {{.End.Lag}})
{{end}}{{end}}<br/>
<br/>
<br/>
More information at <a href="https://robinhood.atlassian.net/wiki/spaces/BO/pages/153518105/Burrow+Kafka+Consumer+Group+Monitoring+go+burrow">http://go/burrow</a> (go/ links require VPN)<br/><br/>


Sent from role kafka-offset-monitor @ 10.1.17.79<br/>

----------------------------------------------------------------------<br/><br/>
{{end}}
</body>
</html>
```
```
goroutine 1 [running]:
main.handleExit()
	/Users/dennis/go/src/github.com/linkedin/Burrow/main.go:63 +0x293
panic(0x920c20, 0xc420178c70)
	/usr/local/go/src/runtime/panic.go:491 +0x283
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc4200a0370, 0x0, 0x0, 0x0)
	/Users/dennis/go/src/go.uber.org/zap/zapcore/entry.go:229 +0x52e
go.uber.org/zap.(*Logger).Panic(0xc42004f0e0, 0xa10684, 0x1e, 0x0, 0x0, 0x0)
	/Users/dennis/go/src/go.uber.org/zap/logger.go:225 +0x7f
github.com/linkedin/Burrow/core.configureCoordinators.func1(0xc42004eae0)
	/Users/dennis/go/src/github.com/linkedin/Burrow/core/burrow.go:96 +0x87
panic(0x920c20, 0xc420178c60)
	/usr/local/go/src/runtime/panic.go:491 +0x283
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc4200a0370, 0xc420010980, 0x2, 0x2)
	/Users/dennis/go/src/go.uber.org/zap/zapcore/entry.go:229 +0x52e
go.uber.org/zap.(*Logger).Panic(0xc42004f380, 0xa10684, 0x1e, 0xc420010980, 0x2, 0x2)
	/Users/dennis/go/src/go.uber.org/zap/logger.go:225 +0x7f
github.com/linkedin/Burrow/core/internal/notifier.(*Coordinator).Configure(0xc420010680)
	/Users/dennis/go/src/github.com/linkedin/Burrow/core/internal/notifier/coordinator.go:216 +0xeb8
github.com/linkedin/Burrow/core.configureCoordinators(0xc42004eae0, 0xcc89e0, 0xc42004bcc0, 0xcc89a0, 0xc420166e70, 0xcc87a0, 0xc4200db120, 0xcc8860, 0xc4200db180, 0xcc88a0, ...)
	/Users/dennis/go/src/github.com/linkedin/Burrow/core/burrow.go:103 +0x9c
github.com/linkedin/Burrow/core.Start(0xc42004eae0, 0xc42004ea20, 0x0)
	/Users/dennis/go/src/github.com/linkedin/Burrow/core/burrow.go:148 +0x372
main.main()
	/Users/dennis/go/src/github.com/linkedin/Burrow/main.go:107 +0x401
Reading configuration from .
{"level":"info","ts":1516410811.4474406,"msg":"Started Burrow"}
{"level":"info","ts":1516410811.4475093,"msg":"configuring","type":"coordinator","name":"zookeeper"}
{"level":"info","ts":1516410811.448042,"msg":"configuring","type":"coordinator","name":"storage"}
{"level":"info","ts":1516410811.449228,"msg":"configuring","type":"module","coordinator":"storage","class":"inmemory","name":"default"}
{"level":"info","ts":1516410811.4493139,"msg":"configuring","type":"coordinator","name":"evaluator"}
{"level":"info","ts":1516410811.449347,"msg":"configuring","type":"module","coordinator":"evaluator","class":"caching","name":"default"}
{"level":"info","ts":1516410811.449374,"msg":"configuring","type":"coordinator","name":"httpserver"}
{"level":"info","ts":1516410811.4494565,"msg":"configuring","type":"coordinator","name":"notifier"}
{"level":"panic","ts":1516410811.4496694,"msg":"Failed to compile TemplateOpen","type":"coordinator","name":"notifier","error":"template: email.tmpl:13: function \"Result\" not defined","module":"dennis"}
{"level":"panic","ts":1516410811.449687,"msg":"Failed to compile TemplateOpen"}
panic: Failed to compile TemplateOpen [recovered]
	panic: Failed to compile TemplateOpen [recovered]
	panic: Failed to compile TemplateOpen

goroutine 1 [running]:
main.handleExit()
	/Users/dennis/go/src/github.com/linkedin/Burrow/main.go:63 +0x293
panic(0x920c20, 0xc4201a8ac0)
	/usr/local/go/src/runtime/panic.go:491 +0x283
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc4200c0370, 0x0, 0x0, 0x0)
	/Users/dennis/go/src/go.uber.org/zap/zapcore/entry.go:229 +0x52e
go.uber.org/zap.(*Logger).Panic(0xc42008d0e0, 0xa10684, 0x1e, 0x0, 0x0, 0x0)
	/Users/dennis/go/src/go.uber.org/zap/logger.go:225 +0x7f
github.com/linkedin/Burrow/core.configureCoordinators.func1(0xc42008cae0)
	/Users/dennis/go/src/github.com/linkedin/Burrow/core/burrow.go:96 +0x87
panic(0x920c20, 0xc4201a8ab0)
	/usr/local/go/src/runtime/panic.go:491 +0x283
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc4200c0370, 0xc420144880, 0x2, 0x2)
	/Users/dennis/go/src/go.uber.org/zap/zapcore/entry.go:229 +0x52e
go.uber.org/zap.(*Logger).Panic(0xc42008d380, 0xa10684, 0x1e, 0xc420144880, 0x2, 0x2)
	/Users/dennis/go/src/go.uber.org/zap/logger.go:225 +0x7f
github.com/linkedin/Burrow/core/internal/notifier.(*Coordinator).Configure(0xc420144580)
	/Users/dennis/go/src/github.com/linkedin/Burrow/core/internal/notifier/coordinator.go:216 +0xeb8
github.com/linkedin/Burrow/core.configureCoordinators(0xc42008cae0, 0xcc89e0, 0xc42008fc80, 0xcc89a0, 0xc420190e10, 0xcc87a0, 0xc4201010a0, 0xcc8860, 0xc420101100, 0xcc88a0, ...)
	/Users/dennis/go/src/github.com/linkedin/Burrow/core/burrow.go:103 +0x9c
github.com/linkedin/Burrow/core.Start(0xc42008cae0, 0xc42008c9c0, 0x0)
	/Users/dennis/go/src/github.com/linkedin/Burrow/core/burrow.go:148 +0x372
main.main()
	/Users/dennis/go/src/github.com/linkedin/Burrow/main.go:107 +0x401
```

Also, can you provide an example of the email config? It's as if the message is implying I need a "Result" in the config.toml somewhere?

I'm running from commit e3a1493b490b7251df63d884c37341f8cb564b1c

**Comment by daodennis** [comment]
This is my email config fwiw:

```
[notifier.dennis]
class-name="email"
interval=300
threshold=2
send-close=true
template-open="email.tmpl"
template-close="email.tmpl"
server="server.domain.com"
port="587"
from="from@domain.com"
to="dennis@domain.com"
auth-type="plain"
username="username"
password="password"
```

**Comment by toddpalino** [comment]
The issue you're running into here is that this line is badly formed:
```
Cluster:  {{Result..Cluster}}<br/>
```

I think you intend that to be this:
```
Cluster:  {{.Result.Cluster}}<br/>
```

I agree that the error messages here are painful. Golang's templating is not what you would consider to be a shining example of usability.

**Comment by daodennis** [comment]
I tried `{{.Result.Cluster}}` and another traceback came my way. I'm following this template for the most part aside from converting it to HTML
https://github.com/linkedin/Burrow/blob/master/config/default-email.tmpl

**Comment by daodennis** [comment]
If I delete that line this is the traceback:

```
{"level":"panic","ts":1516413088.2906032,"msg":"Failed to compile TemplateOpen","type":"coordinator","name":"notifier","error":"template: email.tmpl:27: unexpected {{end}}","module":"dennis"}
```

**Comment by daodennis** [comment]
Todd fixed this https://github.com/linkedin/Burrow/commit/b75a6f377810a4ea6f36002c107b2e3137501c22
