### ISSUE TITLE
SIGSEGV from ringval update in inmemory.go.

### ISSUE THREAD

**Issue by rgevers** [linkedin/Burrow#339]
I'm still doing some troubleshooting on this one but while running the latest updates locally the Burrow process is dying after a few minutes with the following stderr statement.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1494fb3]

goroutine 73 [running]:
github.com/linkedin/Burrow/core/internal/storage.(*InMemoryStorage).addBrokerOffset(0xc420244000, 0xc4209ec8c0, 0xc4209823c0)
	/Users/rgevers/go/src/github.com/linkedin/Burrow/core/internal/storage/inmemory.go:261 +0x293
github.com/linkedin/Burrow/core/internal/storage.(*InMemoryStorage).(github.com/linkedin/Burrow/core/internal/storage.addBrokerOffset)-fm(0xc4209ec8c0, 0xc4209823c0)
	/Users/rgevers/go/src/github.com/linkedin/Burrow/core/internal/storage/inmemory.go:169 +0x3e
github.com/linkedin/Burrow/core/internal/storage.(*InMemoryStorage).requestWorker(0xc420244000, 0x12, 0xc42007ca20)
	/Users/rgevers/go/src/github.com/linkedin/Burrow/core/internal/storage/inmemory.go:186 +0x1003
created by github.com/linkedin/Burrow/core/internal/storage.(*InMemoryStorage).Start
	/Users/rgevers/go/src/github.com/linkedin/Burrow/core/internal/storage/inmemory.go:140 +0x330
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1494fb3]

goroutine 67 [running]:
github.com/linkedin/Burrow/core/internal/storage.(*InMemoryStorage).addBrokerOffset(0xc420244000, 0xc4209ec850, 0xc4209ea1e0)
	/Users/rgevers/go/src/github.com/linkedin/Burrow/core/internal/storage/inmemory.go:261 +0x293
github.com/linkedin/Burrow/core/internal/storage.(*InMemoryStorage).(github.com/linkedin/Burrow/core/internal/storage.addBrokerOffset)-fm(0xc4209ec850, 0xc4209ea1e0)
	/Users/rgevers/go/src/github.com/linkedin/Burrow/core/internal/storage/inmemory.go:169 +0x3e
github.com/linkedin/Burrow/core/internal/storage.(*InMemoryStorage).requestWorker(0xc420244000, 0xc, 0xc42007c7e0)
	/Users/rgevers/go/src/github.com/linkedin/Burrow/core/internal/storage/inmemory.go:186 +0x1003
created by github.com/linkedin/Burrow/core/internal/storage.(*InMemoryStorage).Start
	/Users/rgevers/go/src/github.com/linkedin/Burrow/core/internal/storage/inmemory.go:140 +0x330

```

**Comment by rgevers** [comment]
Provided a quick warn if the type check failed. When we do hit this it's across all topics. Still looking at what would cause that to fail. This does keep Burrow alive though.
`} else {
		ringval, ok := partitionEntry.Value.(*protocol.ConsumerOffset)
		if !ok {
			requestLogger.Warn("incorrect type for offset")
		} else {
			ringval.Offset = request.Offset
			ringval.Timestamp = request.Timestamp
		}`

**Comment by toddpalino** [comment]
It's a bad cast in the new new code for #338. Looks like that branch isn't covered by a test right now

**Comment by toddpalino** [comment]
I just created #340 with the fix. One line of code change, and a new test to catch this problem if it happens again.

**Comment by rgevers** [comment]
Thanks!

**Comment by toddpalino** [comment]
Pushed to master. Should be all set now.

**Comment by jrnt30** [comment]
@toddpalino Not to pile on here, I can open a new issue if you prefer, but I am seeing something similar here off of master.

```goroutine 69 [running]:
github.com/linkedin/Burrow/core/internal/storage.(*InMemoryStorage).fetchTopic(0xc42022e000, 0xc4200f7f10, 0xc420200fc0)
	/go/src/github.com/linkedin/Burrow/core/internal/storage/inmemory.go:611 +0x178
github.com/linkedin/Burrow/core/internal/storage.(*InMemoryStorage).(github.com/linkedin/Burrow/core/internal/storage.fetchTopic)-fm(0xc4200f7f10, 0xc420200fc0)
	/go/src/github.com/linkedin/Burrow/core/internal/storage/inmemory.go:178 +0x3e
github.com/linkedin/Burrow/core/internal/storage.(*InMemoryStorage).requestWorker(0xc42022e000, 0x12, 0xc420174a80)
	/go/src/github.com/linkedin/Burrow/core/internal/storage/inmemory.go:186 +0x1003
created by github.com/linkedin/Burrow/core/internal/storage.(*InMemoryStorage).Start
	/go/src/github.com/linkedin/Burrow/core/internal/storage/inmemory.go:140 +0x330```
