### ISSUE TITLE
Slack Notfication is not working.

### ISSUE THREAD

**Issue by senthil13** [linkedin/Burrow#379]
Hi,
Using the latest Burrow, Configured for slack but its not working. please let me know where its failing

#[notifier.slack]
#class-name="slack"
#interval=30
#threshold=3
#timeout=5
#keepalive=30
#channel="******"
#username="**********"
#template-open="/app/burrow/config/default-slack-post.tmpl"
#url-open="******"

```
[go@negocd-wc-4p burrow]$ cat burrow.out.2018-03-30_19:18:59
panic: Unknown notifier className provided: slack [recovered]
        panic: Unknown notifier className provided: slack [recovered]
        panic: Unknown notifier className provided: slack

goroutine 1 [running]:
main.handleExit()
        /home/travis/gopath/src/github.com/linkedin/Burrow/main.go:63 +0x293
panic(0x8f8c00, 0xc42022c220)
        /home/travis/.gimme/versions/go1.9.2.linux.amd64/src/runtime/panic.go:491 +0x283
github.com/linkedin/Burrow/vendor/go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc420098370, 0x0, 0x0, 0x0)
        /home/travis/gopath/src/github.com/linkedin/Burrow/vendor/go.uber.org/zap/zapcore/entry.go:229 +0x52e
github.com/linkedin/Burrow/vendor/go.uber.org/zap.(*Logger).Panic(0xc42005afc0, 0xc420012ff0, 0x2a, 0x0, 0x0, 0x0)
        /home/travis/gopath/src/github.com/linkedin/Burrow/vendor/go.uber.org/zap/logger.go:225 +0x7f
github.com/linkedin/Burrow/core.configureCoordinators.func1(0xc42005a9c0)
        /home/travis/gopath/src/github.com/linkedin/Burrow/core/burrow.go:96 +0x87
panic(0x8f8c00, 0xc42022c210)
        /home/travis/.gimme/versions/go1.9.2.linux.amd64/src/runtime/panic.go:491 +0x283
github.com/linkedin/Burrow/core/internal/notifier.getModuleForClass(0xc42005a9c0, 0xc42014be78, 0x5, 0xc42014b130, 0x5, 0x0, 0x0, 0xc42022e300, 0xc420059340, 0x0, ...)
        /home/travis/gopath/src/github.com/linkedin/Burrow/core/internal/notifier/coordinator.go:147 +0xa6b
github.com/linkedin/Burrow/core/internal/notifier.(*Coordinator).Configure(0xc4200ec600)
        /home/travis/gopath/src/github.com/linkedin/Burrow/core/internal/notifier/coordinator.go:230 +0x714
github.com/linkedin/Burrow/core.configureCoordinators(0xc42005a9c0, 0xca49a0, 0xc420058e80, 0xca4960, 0xc42015c930, 0xca4760, 0xc4200d57e0, 0xca4820, 0xc4200d5840, 0xca4860, ...)
        /home/travis/gopath/src/github.com/linkedin/Burrow/core/burrow.go:103 +0x9c
github.com/linkedin/Burrow/core.Start(0xc42005a9c0, 0xc42005a900, 0x0)
        /home/travis/gopath/src/github.com/linkedin/Burrow/core/burrow.go:148 +0x372
main.main()
        /home/travis/gopath/src/github.com/linkedin/Burrow/main.go:107 +0x401
```

**Comment by marcosArruda** [comment]
I think there is no specific slack notifier anymore. You need to configure an endpoint on your slack team to receive POST messages, then u sent like a basic http request.
