### ISSUE TITLE
kafka client processConsumerOffsetsMessage panic error

### ISSUE THREAD

**Issue by maplebeats** [linkedin/Burrow#497]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0xabb7da]

goroutine 14695 [running]:
github.com/linkedin/Burrow/core/internal/consumer.(*KafkaClient).processConsumerOffsetsMessage(0xc0002d6360, 0x0)
        /home/titustian/go/src/github.com/linkedin/Burrow/core/internal/consumer/kafka_client.go:234 +0x3a
github.com/linkedin/Burrow/core/internal/consumer.(*KafkaClient).partitionConsumer(0xc0002d6360, 0xe58ca0, 0xc00afd81b0)
        /home/titustian/go/src/github.com/linkedin/Burrow/core/internal/consumer/kafka_client.go:171 +0x595
created by github.com/linkedin/Burrow/core/internal/consumer.(*KafkaClient).startKafkaConsumer
        /home/titustian/go/src/github.com/linkedin/Burrow/core/internal/consumer/kafka_client.go:226 +0x91a
```
```golang
func (module *KafkaClient) processConsumerOffsetsMessage(msg *sarama.ConsumerMessage) {
	logger := module.Log.With(
		zap.String("offset_topic", msg.Topic),
		zap.Int32("offset_partition", msg.Partition),
		zap.Int64("offset_offset", msg.Offset),
	)

	if len(msg.Value) == 0 {
		// Tombstone message - we don't handle them for now
		logger.Debug("dropped tombstone")
		return
	}
```
when the msg is nil ,the logger initialize cause a panic。

**Comment by maplebeats** [comment]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xaba573]

goroutine 14292 [running]:
github.com/linkedin/Burrow/core/internal/consumer.(*KafkaClient).partitionConsumer(0xc000204510, 0xe58ee0, 0xc004925680)
        /home/titustian/go/src/github.com/linkedin/Burrow/core/internal/consumer/kafka_client.go:174 +0x1d3
created by github.com/linkedin/Burrow/core/internal/consumer.(*KafkaClient).startKafkaConsumer
        /home/titustian/go/src/github.com/linkedin/Burrow/core/internal/consumer/kafka_client.go:226 +0x91a
```
partitionConsumer has sample question

**Comment by toddpalino** [comment]
I'm a little surprised that Sarama sends nil pointers across those channels. That seems like a bug in Sarama.

Regardless, it should be relatively easy to check and discard in that case.

**Comment by aparmar1** [comment]
I'm getting same error while running burrow docker image. Is there any fix?

`│ panic: runtime error: invalid memory address or nil pointer dereference                                                                                                                                                               │
│ [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x883f53]                                                                                                                                                                │
│ goroutine 892 [running]:                                                                                                                                                                                                              │
│ github.com/linkedin/Burrow/core/internal/consumer.(*KafkaClient).partitionConsumer(0xc000276000, 0xb2e5e0, 0xc000dde000)                                                                                                              │
│     /go/src/github.com/linkedin/Burrow/core/internal/consumer/kafka_client.go:173 +0x1d3                                                                                                                                              │
│ created by github.com/linkedin/Burrow/core/internal/consumer.(*KafkaClient).startKafkaConsumer                                                                                                                                        │
│     /go/src/github.com/linkedin/Burrow/core/internal/consumer/kafka_client.go:225 +0x91a`
