### ISSUE TITLE
Failed to Validate zookeeper server

### ISSUE THREAD

**Issue by msalmanST** [linkedin/Burrow#516]
Hi,

I am facing an issue after upgrading to latest version of burrow i.e 1.2.2 below are the error logs, my kafka version is 2.1.1

> trace{"level":"info","ts":1554803073.380277,"msg":"Started Burrow"}
{"level":"info","ts":1554803073.380725,"msg":"configuring","type":"coordinator","name":"zookeeper"}
{"level":"panic","ts":1554803073.3809888,"msg":"Failed to validate Zookeeper servers"}
panic: Failed to validate Zookeeper servers [recovered]
	panic: Failed to validate Zookeeper servers [recovered]
	panic: Failed to validate Zookeeper servers

> goroutine 1 [running]:
main.handleExit()
	/Users/msalman/go/src/github.com/linkedin/Burrow/main.go:64 +0x259
panic(0x45e3ee0, 0xc0000580b0)
	/usr/local/Cellar/go/1.11.4/libexec/src/runtime/panic.go:513 +0x1b9
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc0001aa000, 0x0, 0x0, 0x0)
	/Users/msalman/go/src/go.uber.org/zap/zapcore/entry.go:229 +0x515
go.uber.org/zap.(*Logger).Panic(0xc0001981e0, 0x46e43ca, 0x24, 0x0, 0x0, 0x0)
	/Users/msalman/go/src/go.uber.org/zap/logger.go:225 +0x7f
github.com/linkedin/Burrow/core.configureCoordinators.func1(0xc000198000)
	/Users/msalman/go/src/github.com/linkedin/Burrow/core/burrow.go:96 +0x7d
panic(0x45e3ee0, 0x47794a0)
	/usr/local/Cellar/go/1.11.4/libexec/src/runtime/panic.go:513 +0x1b9
github.com/linkedin/Burrow/core/internal/zookeeper.(*Coordinator).Configure(0xc00006c080)
	/Users/msalman/go/src/github.com/linkedin/Burrow/core/internal/zookeeper/coordinator.go:64 +0x252
github.com/linkedin/Burrow/core.configureCoordinators(0xc000198000, 0x47810e0, 0xc00006c080, 0x47810a0, 0xc00001e300, 0x4780ea0, 0xc00000c260, 0x4780f60, 0xc00001e3f0, 0x4780fa0, ...)
	/Users/msalman/go/src/github.com/linkedin/Burrow/core/burrow.go:103 +0xaf
github.com/linkedin/Burrow/core.Start(0xc000198000, 0xc0000bcd20, 0x0)
	/Users/msalman/go/src/github.com/linkedin/Burrow/core/burrow.go:148 +0x3b3
main.main()
	/Users/msalman/go/src/github.com/linkedin/Burrow/main.go:115 +0x4d0

**Comment by msalmanST** [comment]
I removed "http://" from the zookeeper address and it worked, may be it help someone in future.
