### ISSUE TITLE
panic: runtime error: index out of range

### ISSUE THREAD

**Issue by vijaytakkoli** [linkedin/Burrow#698]
We are trying to run burrow for one of our test cluster but ended up with the below error 
```
Reading configuration from /etc/burrow
{"level":"info","ts":1619543232.6165488,"msg":"Started Burrow"}
{"level":"info","ts":1619543232.6166623,"msg":"configuring","type":"coordinator","name":"zookeeper"}
{"level":"info","ts":1619543232.617059,"msg":"configuring","type":"coordinator","name":"storage"}
{"level":"info","ts":1619543232.6171033,"msg":"configuring","type":"module","coordinator":"storage","class":"inmemory","name":"default"}
{"level":"info","ts":1619543232.6172295,"msg":"configuring","type":"coordinator","name":"evaluator"}
{"level":"info","ts":1619543232.6172628,"msg":"configuring","type":"module","coordinator":"evaluator","class":"caching","name":"default"}
{"level":"info","ts":1619543232.6173084,"msg":"configuring","type":"coordinator","name":"httpserver"}
{"level":"info","ts":1619543232.617424,"msg":"configuring","type":"coordinator","name":"notifier"}
{"level":"info","ts":1619543232.6174593,"msg":"configuring","type":"coordinator","name":"cluster"}
{"level":"info","ts":1619543232.617493,"msg":"configuring","type":"module","coordinator":"cluster","class":"kafka","name":"ost-ttce-test-ole"}
{"level":"info","ts":1619543232.617794,"msg":"configuring","type":"coordinator","name":"consumer"}
{"level":"info","ts":1619543232.6178439,"msg":"configuring","type":"module","coordinator":"consumer","class":"kafka","name":"ost-ttce-test-ole"}
{"level":"info","ts":1619543232.6181514,"msg":"starting","type":"coordinator","name":"zookeeper"}
{"level":"info","ts":1619543232.6315393,"msg":"Connected to 10.57.152.27:2181","type":"coordinator","name":"zookeeper"}
{"level":"info","ts":1619543232.636245,"msg":"Authenticated: id=5620541488645823474, timeout=12000","type":"coordinator","name":"zookeeper"}
{"level":"info","ts":1619543232.6362965,"msg":"Re-submitting `0` credentials after reconnect","type":"coordinator","name":"zookeeper"}
{"level":"info","ts":1619543232.6401088,"msg":"starting","type":"coordinator","name":"storage"}
{"level":"info","ts":1619543232.640142,"msg":"starting","type":"module","coordinator":"storage","class":"inmemory","name":"default"}
{"level":"info","ts":1619543232.6402085,"msg":"starting","type":"coordinator","name":"evaluator"}
{"level":"info","ts":1619543232.6402225,"msg":"starting","type":"module","coordinator":"evaluator","class":"caching","name":"default"}
{"level":"info","ts":1619543232.6402314,"msg":"starting","type":"coordinator","name":"httpserver"}
{"level":"info","ts":1619543232.6412015,"msg":"started listener","type":"coordinator","name":"httpserver","listener":"[::]:8000"}
{"level":"info","ts":1619543232.6412935,"msg":"starting","type":"coordinator","name":"notifier"}
{"level":"info","ts":1619543232.641335,"msg":"starting","type":"coordinator","name":"cluster"}
{"level":"info","ts":1619543232.6413436,"msg":"starting","type":"module","coordinator":"cluster","class":"kafka","name":"ost-ttce-test-ole"}
{"level":"info","ts":1619543232.7472012,"msg":"starting evaluations","type":"coordinator","name":"notifier"}
panic: runtime error: index out of range

goroutine 117 [running]:
github.com/linkedin/Burrow/core/internal/storage.(*InMemoryStorage).addBrokerOffset(0xc0001fe1e0, 0xc000e75080, 0xc000e87620)
	/go/src/github.com/linkedin/Burrow/core/internal/storage/inmemory.go:264 +0x573
github.com/linkedin/Burrow/core/internal/storage.(*InMemoryStorage).requestWorker(0xc0001fe1e0, 0x13, 0xc0001e5080)
	/go/src/github.com/linkedin/Burrow/core/internal/storage/inmemory.go:202 +0x11d7
created by github.com/linkedin/Burrow/core/internal/storage.(*InMemoryStorage).Start
	/go/src/github.com/linkedin/Burrow/core/internal/storage/inmemory.go:156 +0x289
```

Can you please let us know how to solve this issue

**Comment by SandeepVaman** [comment]
Can you please specify the version of Burrow, Kafka and zookeeper you are using? Also can you please paste burrow config file?
